trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: Cache@2
  inputs:
    key: 'npm | package-lock.json'
    path: 'node_modules'
    cacheHitVar: CACHE_RESTORED
  displayName: 'Cache node_modules'

- script: |
    npm install
  displayName: 'npm install'
  condition: ne(variables.CACHE_RESTORED, 'true')

- script: |
    npm run build
  displayName: 'npm build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build'
    ArtifactName: 'reactapp'
    publishLocation: 'Container'

- task: Docker@2
  inputs:
    containerRegistry: 'devopsdashboard.azurecr.io'
    repository: 'DevopsDashboard'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 
      $(Build.BuildId)